import '../styles/globals.css';
import '../styles/reset.css';
import '../styles/page.css';
import localFont from 'next/font/local';
import Modal from '../components/modal/Modal.jsx';

export const metadata = {
  title: '도이스토리',
  description: 'Generated by 도이',
  icons: {
    icon: '/nav_sprout.png',
  },
};

const pretendard = localFont({
  src: 'fonts/PretendardVariable.woff2',
  display: 'swap',
  variable: '--font-pretendard',
  weight: '400 920',
});

export default function RootLayout({ children }) {
  return (
    <>
      <html>
        <body className={pretendard.variable}>
          <Modal />
          <div className="scroll_top"></div>
          {children}
        </body>
      </html>
    </>
  );
}
