import "./styles/globals.css";
import "./styles/reset.css";
import "./styles/page.css";
import "./styles/media.css";


import Modal from "@/components/modal/Modal.jsx";

export const metadata = {
  title: "도이스토리",
  description: "Generated by 도이",
  icons: {
    icon: "/nav_sprout.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <>
      <html>
        <body>
          <Modal />
          <div className="scroll_top"></div>
          {children}
        </body>
      </html>
    </>
  );
}
