import './globals.css'
import './reset.css'
import Link from "next/link";

export const metadata = {
  title: "도이 포트폴리오",
  description: "Generated by 도이",
  icons: {
    icon: "/tree.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <>
      <html>
        <body>
          <main className="intro">
            <header></header>
            <h1 className="intro_front">FRONT-END</h1>
            <h1 className="intro_developer">DEVELOPER</h1>
            <p className='test'>프론트엔드 개발자 이도이입니다.</p>
          </main>
          {children}
        </body>
      </html>
    </>
  );
}







